# Generated by Django 4.0.4 on 2022-05-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_cart_id_cart_cartitemid_cart_copies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cartItemId',
        ),
        migrations.AddField(
            model_name='cart',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
