# Generated by Django 4.0.4 on 2022-05-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_cart_cartitemid_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ccv',
            field=models.IntegerField(default=0),
        ),
    ]
